### ISSUE TITLE
Support per test capabilities

### ISSUE THREAD

**Issue by soulrebel** [pytest-dev/pytest-splinter#101]
We are currently interested in using Zalenium and Browserstack to provide the Selenium grid which our tests can use. This brings us new requirements on how the browser capabilities are defined and the browser session lifecycle to enable us to set the test name and possibly also the success/failure status.

Rather than a single session scoped capability set, we need to have per test capabilities, parametrized with the test name.

Currently most fixtures have session scope and are used to build another session-scoped ``browser_instance_getter`` fixture that is then used to instantiate the test-scoped browser session, effectively capturing the browser kwargs and the capabilities in the session scope. So a wide refactoring seems to be needed to change this.

While we are at it it would be a plus to provide also some execution hook before the session is closed that could mark the test status (via setting a special cookie to Zalenium).

I am somewhat interested in developing this myself, but I feel it would need quite a change of the codebase and I am not sure how to tackle it without breaking too much.

**Comment by bubenkoff** [comment]
@soulrebel, can't you parametrize session-scoped fixture and then test will be executed several times?
related to #92

**Comment by soulrebel** [comment]
I have gotten a bit out of touch on this, but it looks related yes.
