### ISSUE TITLE
config.warn is not supported in pytest 4

### ISSUE THREAD

**Issue by jsfehler** [pytest-dev/pytest-splinter#117]
When a screenshot cannot be saved, the following message appears:

```RemovedInPytest4Warning: config.warn has been deprecated, use warnings.warn instead```

**Comment by youtux** [comment]
This should be fixed by #116

**Comment by youtux** [comment]
I just released version 2.0.1 on PyPI, I'm closing the case because the issue should be fixed now. Thanks for your report!
