### ISSUE TITLE
Overriding splinter_screenshot_dir fixture doesn't work with pytest-xdist

### ISSUE THREAD

**Issue by jsfehler** [pytest-dev/pytest-splinter#119]
When pytest-xdist is used, the screenshot directory location is stored during pytest_configure. As a result, overriding splinter_screenshot_dir in a conftest.py file has no effect.

**Comment by yegorLitvinov** [comment]
@jsfehler Looks like this bug was fixed in one of the latest releases. I had the same issue and now it's gone.

**Comment by mpasternak** [comment]
Closing, based on inactivity and a suggestion from @yegorLitvinov that this is no longer a problem. In case this is wrong please let me know.
