### ISSUE TITLE
Any API to reset the state of the browser? Clean cookies etc.?

### ISSUE THREAD

**Issue by sureshvv** [pytest-dev/pytest-splinter#124]
This will be useful to me

**Comment by sureshvv** [comment]
I was able to use

splinter-session-scoped-browser=false

**Comment by bubenkoff** [comment]
@sureshvv browser state should be clean without making it function scoped, otherwise you get a big performance drawback. We clear the cookies for every test, doesn't it happen for you?

**Comment by sureshvv** [comment]
Actually these are client side cookies saved in localstorage. So I don't think it is a pytest-splinter problem.
