### ISSUE TITLE
Reenable browser resizing in chrome

### ISSUE THREAD

**Issue by rnovacek** [pytest-dev/pytest-splinter#135]
This line skips browser resizing in Chrome, but referenced bug is already fixed and resizing works fine with recent versions of chromedriver: 
https://github.com/pytest-dev/pytest-splinter/blob/master/pytest_splinter/plugin.py#L559

See referenced issue: https://github.com/SeleniumHQ/selenium/issues/3508

**Comment by bubenkoff** [comment]
please make PR

**Comment by rnovacek** [comment]
Ah, I just tested and it doesn't work. This one works fine:

```
@pytest.fixture
def browser(request, browser_instance_getter):
    b = browser_instance_getter(request, browser)
    b.driver.set_window_size(1920, 1080)
    return b
```

But this one doesn't:
```
@pytest.fixture(scope='session')
def splinter_window_size():
    return 1920, 1080
```

No idea why. Maybe the browser is not properly initialized when doing the fixture size...

**Comment by bubenkoff** [comment]
try to wait some time, just to make sure?

**Comment by mpasternak** [comment]
@rnovacek is the issue still problematic? Could you please submit a working PR?

**Comment by rnovacek** [comment]
I no longer use it, sorry. Feel free to close the issue.

**Comment by mpasternak** [comment]
We had some changes to README.rst and there's a snippet that changes Chrome's window size. Maybe the method is different but, well, if you need it, there it is. Closing, if somebody is interested in this particular approach, please reopen. Thanks for the report.
