### ISSUE TITLE
Splinter 0.18.0: `AttributeError: module 'splinter.driver.webdriver.firefox' has no attribute 'WebDriverElement'`

### ISSUE THREAD

**Issue by kalekseev** [pytest-dev/pytest-splinter#158]
### Problem

```
============================================================================================ ERRORS =============================================================================================
_____________________________________________________________________________ ERROR at setup of test_file ______________________________________________________________________________

    @pytest.fixture(scope="session")
    def browser_patches():
        """Browser monkey patches."""
        patch_webdriver()
>       patch_webdriverelement()

.direnv/python-3.9.12/lib/python3.9/site-packages/pytest_splinter/plugin.py:278:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    def patch_webdriverelement():  # pragma: no cover
        """Patch the WebDriverElement to allow firefox to use mouse_over."""

        def mouse_over(self):
            """Perform a mouse over the element which works."""
            (
                ActionChains(self.parent.driver)
                .move_to_element_with_offset(self._element, 2, 2)
                .perform()
            )

        # Apply the monkey patch for Firefox WebDriverElement
>       firefox.WebDriverElement.mouse_over = mouse_over
E       AttributeError: module 'splinter.driver.webdriver.firefox' has no attribute 'WebDriverElement'

.direnv/python-3.9.12/lib/python3.9/site-packages/pytest_splinter/splinter_patches.py:21: AttributeError
==================================================================================== short test summary info ====================================================================================
ERROR test_file.py::test_file - AttributeError: module 'splinter.driver.webdriver.firefox' has no attribute 'WebDriverElement'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================================= 1 error in 0.63s ========================================================================================

```

### Temporary workaround

`patch_webdriverelement` can be disabled by overriding fixture

```
from pytest_splinter.webdriver_patches import patch_webdriver

@pytest.fixture(scope="session")
def browser_patches():
    patch_webdriver()
```

**Comment by mpasternak** [comment]
Patch works! @kalekseev , you're a life-saver @kalekseev , thanks!

It looks like WebDriverElement was moved to splinter.driver.webdriver module and BaseWebDriver uses it as self.element_class. I don't think that monkey-patching BaseWebDriver is the way to go - on the other hand if there's a limitation "single test session == single web driver" it should be okay. 

If any pytest-dev is willing to provide me support on this, I can provide a PR. For the simpler case :-)

**Comment by kalekseev** [comment]
@mpasternak you can try and test if that monkeypatch is still needed for firefox https://github.com/pytest-dev/pytest-splinter/blob/0ee5590c469b27221e7a93980cc163a195a42014/pytest_splinter/splinter_patches.py#L12-L18 
It's probably not needed because https://github.com/cobrateam/splinter/blob/master/docs/news/0.7.0.rst#features

> Support for mouse_over, mouse_out in Firefox driver.

In that case you can safely remove `patch_webdriverelement`

**Comment by mpasternak** [comment]
This should be fixed for now in trunk. Unfortunately ATM #163 I'm unable to run test, because all I get is "flask" webriver...

**Comment by mpasternak** [comment]
@kalekseev as the CI is working again -- please check if the recent changes in the codebase fixed this problem. Is your patch still needed?

**Comment by kalekseev** [comment]
`pip install https://github.com/pytest-dev/pytest-splinter/archive/master.tar.gz` works

**Comment by mpasternak** [comment]
@kalekseev thank you for both the problem report and the initial patch idea, as it saved my life. Looks like it is no longer relevant - closing it. Thanks!
