### ISSUE TITLE
Travis-CI stopped building things some time ago 

### ISSUE THREAD

**Issue by mpasternak** [pytest-dev/pytest-splinter#160]
We need to move this to GitHub actions because of admin settings I'm unable to merge anything as long as the CI is not working. 

I have a pretty simple way of converting things, which requires ``tox-gh-actions`` and its really straightforward, see: https://github.com/yourlabs/django-session-security/blob/master/.github/workflows/tests.yml

**Comment by bubenkoff** [comment]
please let me know if you need some access in order to implement it, but you should be able to do it yourself?

**Comment by mpasternak** [comment]
Working on it.

**Comment by mpasternak** [comment]
I created a PR but I need a review AND a passing CI @bubenkoff . 

This probably means you need to disable those CI checks for now, then merge, then get GitHub Actions working, then re-enable them. 

While we're at it, you could merge #159 which I reviewed.
