### ISSUE TITLE
I'm unable to make splinter on CI return anything else than "flask" webdriver

### ISSUE THREAD

**Issue by mpasternak** [pytest-dev/pytest-splinter#164]
Hi, 

PR: #163 

All I get on CI is "flask" web driver. There is Firefox installed, there is gecko driver executable, I even made it download Selenium - just like the old times - and I'm unable to replicate this on my local setup. 

If anybody has any ideas please help, we could have working CI by now if not that bug.

**Comment by mpasternak** [comment]
Logs: https://github.com/mpasternak/pytest-splinter/runs/7590815131?check_suite_focus=true 

Log file: https://github.com/mpasternak/pytest-splinter/commit/57c936f81e2c48cb65e4420389b47f4bbdc6e832/checks/7590815131/logs

**Comment by mpasternak** [comment]
Looks like recent splinter installation is componentized, eg you install ``pip install splinter[selenium4,django,flask]``

**Comment by mpasternak** [comment]
After adding this type of installation I still get those strange errors. @bubenkoff I don't think I have enough knowledge about Splinter and/or Pytest-Splinter to really find out why does it get such strange drives... on a remote CI. 

I need to setup another machine (x86 because I'm on M1 Mac now) to simulate GitHub running environment, maybe this will give me some insights. As for now, I'll merge what I came up with and wait for someone else to fix it.

**Comment by kalekseev** [comment]
@mpasternak I haven't investigated much but most probably tox does something with environment, if you run pytest it works, I created PR with example https://github.com/pytest-dev/pytest-splinter/pull/165
The PR is failing because of remote driver tests but they fail on local run too.

**Comment by mpasternak** [comment]
@kalekseev thank you for your help, very appreciated. 

Maybe this is an idea. 

Maybe GA should not run tox but pytest directly? Downside: this way we will actually have two CI configurations, tox and GA. Upside: it will work. 

@bubenkoff what do you think?

**Comment by kalekseev** [comment]
@mpasternak I'd say until devs need to run CIs jobs locally theres no much value in tox while overhead is considerable

**Comment by mpasternak** [comment]
Looks like I am convinced.

@kalekseev I merged #165 as it actually does what was previously done. 

Would you like to add GitHub Python versions CI matrix to your branch? Just like described here: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow . If yes, let me know and I'll review and commit. 

What we would then need is all the other targets supported by tox -- but running lint via tox, like "tox -e lint" will probably work. Eh, it would be better to keep configuration in one place (tox.ini)... on the other hand it is better to have working CI...

**Comment by mpasternak** [comment]
@kalekseev don't bother with the Python matrix, I'll probably do that later, I just seen that it's really simple to do and I already had it in my branch. So thanks for inspiration & sorry for asking

**Comment by kalekseev** [comment]
> @kalekseev don't bother with the Python matrix, I'll probably do that later, I just seen that it's really simple to do and I already had it in my branch. So thanks for inspiration & sorry for asking

https://github.com/kalekseev/django-extra-checks/blob/master/.github/workflows/main.yml workflow that I use to test my python library

> What we would then need is all the other targets supported by tox -- but running lint via tox, like "tox -e lint" will probably work. 

pre-commit is superior for liniting https://github.com/kalekseev/django-extra-checks/blob/master/.pre-commit-config.yaml, it fixes/shows problems on commit and can be used on CI, see lint job in my workflow for inspiration
