### ISSUE TITLE
browser.status_code not available

### ISSUE THREAD

**Issue by alvinchow86** [pytest-dev/pytest-splinter#2]
I tried to access "status_code" from the browser fixture but it appears to be missing? 

```
print browser.status_code   # get AttributeError
```
returns 
```
E       AttributeError: 'WebDriver' object has no attribute 'status_code'

venv/lib/python2.7/site-packages/pytest_splinter/plugin.py:29: AttributeError
```

http://splinter.cobrateam.info/docs/http-status-code-and-exception.html

**Comment by blueyed** [comment]
> but this compensation requires an additional request which slows down the whole test process

Would it be possible to do this extra request lazily, when/if `status_code` gets accessed?

> if you feel it absolutely required, let's have a fixture which will control this (enabling the status code)?

That would be nice.

My use case is to check for `status_code.is_success`, just to make sure that the page is generated successfully.
This could be achieved (somehow) by `assert "" not in browser.html`, but using the `status_code` would be better.

**Comment by bubenkoff** [comment]
I'll take a look, thanks

**Comment by blueyed** [comment]
Thanks!
For the time being, please consider re-opening the issue, so that it does not get lost.

**Comment by bubenkoff** [comment]
1.2.8 is out!

**Comment by bubenkoff** [comment]
oops, found out that status_code wasn't cleared on visit, now it's ok
1.2.9 is there, please try

**Comment by blueyed** [comment]
Sorry for the late reply, works as advertised! :)
Thanks!
