### ISSUE TITLE
Long initialization time

### ISSUE THREAD

**Issue by santagada** [pytest-dev/pytest-splinter#27]
For even one simple test pytest-splinter takes up to 40 seconds. I don't remember this being the case, it only took something like 10 seconds to start the driver before. Is anyone else seeing this?

**Comment by bubenkoff** [comment]
can you please make 2 tests with or without pytest-splinter to compare the times?

**Comment by santagada** [comment]
I saw that it was actually happening because I have pytest-bdd installed, even if not using it apparently. I will reopen it on pytest-bdd when I have the time.

**Comment by bubenkoff** [comment]
pytest-bdd parses all the feature files on import time, once
if you have them a lot then it's logical
but im sure there's a room for optimisation

On 19 May 2015 at 04:33, Leonardo Santagada <notifications@github.com>
wrote:

> I saw that it was actually happening because I have pytest-bdd installed,
> even if not using it apparently. I will reopen it on pytest-bdd when I have
> the time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pytest-dev/pytest-splinter/issues/27#issuecomment-103306472>
> .
>



-- 
Anatoly Bubenkov
