### ISSUE TITLE
select splinter webdriver

### ISSUE THREAD

**Issue by luzfcb** [pytest-dev/pytest-splinter#30]
hello, how do I configure pytest-splinter to use another splinter webdriver, without using a command line parameter?

I didn't think very clear documentation about it.
Could you provide any examples, and include it in the documentation?

I'm still learning py.test, but i already know how to do some things with splinter
thanks.

**Comment by bubenkoff** [comment]
you need to override a fixture `splinter_webdriver` in your conftest like:

```
import pytest

@pytest.fixture(scope='session')
def splinter_webdriver():
    """Override splinter webdriver name."""
    return 'some-other-driver'
```

**Comment by OpenTrading** [comment]
Could you add this to the documentation and explain it.

Also, could you document which splinter drivers are supported, and add the
supported drivers to the tests - I think the only driver that's tested is firefox.

**Comment by OpenTrading** [comment]
With splinter_webdriver() = 'phantomjs',  phantomjs-2.0.0, pytest_localserver-0.3.4,
splinter-0.7.2, Python2.7.9 on Linux, the tests fail:

3 failed, 20 passed, 1 skipped, 2 warnings in 45.78 seconds 

Some of the failures are because of
https://github.com/pytest-dev/pytest-splinter/issues/31

**Comment by OpenTrading** [comment]
With splinter_webdriver() = 'zope.testbrowser', zope.testbrowser=4.0.4, pytest_localserver-0.3.4,
splinter-0.7.2, Python2.7.9 on Linux, all the zope.testbrowser  tests fail:

10 passed, 1 skipped, 13 error in 11.69 seconds 

See https://github.com/pytest-dev/pytest-splinter/issues/33

**Comment by bubenkoff** [comment]
i think it's mentioned already, but i'll emphasize, thanks

**Comment by luzfcb** [comment]
@bubenkoff It worked perfectly. thanks
