### ISSUE TITLE
tests_require=['tox', 'pytest-localserver'],

### ISSUE THREAD

**Issue by OpenTrading** [pytest-dev/pytest-splinter#32]
The tests require that `pytest-localserver`  be installed to define the
funcarg `httpserver`.

Could you document this requirement, and `setup.py` should be changed to have
```
tests_require=['tox', 'pytest-localserver'],
```

Actually, `tox` is not required, just supported.

**Comment by bubenkoff** [comment]
See requirements-testing.txt
The only direct test requirement is to
Then it installs test deps from pip config
