### ISSUE TITLE
AttributeError: 'ZopeTestBrowser' object has no attribute 'driver'

### ISSUE THREAD

**Issue by OpenTrading** [pytest-dev/pytest-splinter#33]
With splinter_webdriver() = 'zope.testbrowser', zope.testbrowser=4.0.4, pytest_localserver-0.3.4,
splinter-0.7.2, Python2.7.9 on Linux, all the zope.testbrowser tests fail:

10 passed, 1 skipped, 13 error in 11.69 seconds 

The main problem is:
>           browser.driver.implicitly_wait(splinter_selenium_implicit_wait)
E           AttributeError: 'ZopeTestBrowser' object has no attribute 'driver'

The tests currently only test the default which is firefox, and the documentation
doesn't mention that it's the only supported driver.

**Comment by bubenkoff** [comment]
Thanks I'll check
But off is not the only working one
Chrome phantom js as well
