### ISSUE TITLE
test_download_file tests fail with py.test --splinter-webdriver=phantomjs

### ISSUE THREAD

**Issue by OpenTrading** [pytest-dev/pytest-splinter#35]
In addition to the failure in firefox of the current github.com code
https://github.com/pytest-dev/pytest-splinter/issues/31
both test_download_file tests fail with py.test --splinter-webdriver=phantomjs

 linux2 -- Python 2.7.10 -- py-1.4.27 -- pytest-2.7.0

>       assert open(os.path.join(splinter_file_download_dir, file_name)).read() == 'Some text file'
E       IOError: [Errno 2] No such file or directory: '/var/tmp/pytest-47/pytest_splinter0/some.pdf'

browser    = <splinter.driver.webdriver.phantomjs.WebDriver object at 0xb426a74c>
file_extension = 'pdf'
file_name  = 'some.pdf'
httpserver = <ContentServer(<class 'pytest_localserver.http.ContentServer'>, started -1276011712)>
mime_type  = 'application/pdf'
splinter_file_download_dir = '/var/tmp/pytest-47/pytest_splinter0'

test_plugin.py:66: IOError
------------------------------- Captured stderr call -------------------------------
127.0.0.1 - - [11/Jun/2015 08:41:15] "GET / HTTP/1.1" 200 -
=========== 3 failed, 20 passed, 1 skipped, 2 warnings in 35.34 seconds

**Comment by bubenkoff** [comment]
phantomjs doesn't handle this https://github.com/ariya/phantomjs/issues/10052

**Comment by OpenTrading** [comment]
Can you parametrize the test so that it's excluded if the webdriver is phantomjs?
Or catch the failure for phantomjs to show that it is expected:
in a piece of testing software, it's expected that the tests pass :-)

phantomjs also fails like firefox on https://github.com/pytest-dev/pytest-splinter/issues/31
