### ISSUE TITLE
Extend Browser class

### ISSUE THREAD

**Issue by ecesena** [pytest-dev/pytest-splinter#36]
Hi, is there an easy way to extend the class Browser with a class MyBrowser?

**Comment by bubenkoff** [comment]
Not atm, but we can refactor it to be a fixture, browser_class or something like that.
Pr is welcome

**Comment by bubenkoff** [comment]
1.4.0 is out
so you can override a `splinter_browser_class` fixture
and have your own class derived from `pytest_splinter.plugin.Browser` class which is default

**Comment by ecesena** [comment]
Cool thanks! Sorry for the delay...
