### ISSUE TITLE
Как работать с общей БД?

### ISSUE THREAD

**Issue by qari** [pytest-dev/pytest-splinter#38]
Суть проблемы в том, что сервер (runserver) запущен с параметрами

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
а тесты запускает отдельной БД. Использую django 1.8, pytest-bdd и pytest-splinter.

Пробовал запускать сервер с указанием БД такой как при тестировании. В итоге тесты проходят на отдельной БД. Может конфиг нужен какойто

**Comment by bubenkoff** [comment]
please translate it to english so everyone can understand
