### ISSUE TITLE
TypeError: tmpdir() missing 1 required positional argument: 'tmpdir_factory'

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-splinter#39]
I am seeing an error when using pytest master with pytest-splinter master:

    ERROR at setup of test_foo

    request = <SubRequest 'session_tmpdir' for <Function 'test_foo'>>

        @pytest.fixture(scope='session')
        def session_tmpdir(request):
            """pytest tmpdir which is session-scoped."""
    >       return tmpdir(request)
    E       TypeError: tmpdir() missing 1 required positional argument: 'tmpdir_factory'

    request    = <SubRequest 'session_tmpdir' for <Function 'test_submitter_persons'>>

    …/pytest-splinter/pytest_splinter/plugin.py:246: TypeError

**Comment by bubenkoff** [comment]
this is now solved
thanks!
