### ISSUE TITLE
Saving HTML on test failure

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-splinter#40]
Similar to taking screenshots on test failure, I think that saving the HTML, with some replacements, seems to be useful.

This can be basically achieved by:

    open("/tmp/t.html", "w").write(browser.html)

And the replacing `"/static/` with `"http://localhost:8000/static/`.

What do you think?
Would that be useful to ship (and possibly enable) by default?

**Comment by bubenkoff** [comment]
nice idea!
screenshots are not copy-pasteable, but this will be rendered natively, for example in jenkins it will be no problem to set up via plugins
that will be really cool
i think we can use native feature of saving a page offline from the browser, but didn't try that yet
do you mind of working on this?

**Comment by bubenkoff** [comment]
implemented in 1.6.0 :)
