### ISSUE TITLE
Crash in retry

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest-splinter#47]
Here is a traceback, I have not digged into the details:

```
.tox/py27/src/splinter/splinter/driver/webdriver/__init__.py:522: in fill
    self.value = value
.tox/py27/src/splinter/splinter/driver/webdriver/__init__.py:508: in _set_value
    self._element.clear()
.tox/py27/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py:77: in clear
    self._execute(Command.CLEAR_ELEMENT)
.tox/py27/local/lib/python2.7/site-packages/selenium/webdriver/remote/webelement.py:448: in _execute
    return self._parent.execute(command, params)
.tox/py27/local/lib/python2.7/site-packages/pytest_splinter/webdriver_patches.py:48: in execute
    result = self._base_execute(driver_command, params)
.tox/py27/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py:194: in execute
    response = self.command_executor.execute(driver_command, params)
.tox/py27/local/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py:395: in execute
    return self._request(command_info[0], url, body=data)
.tox/py27/local/lib/python2.7/site-packages/pytest_splinter/webdriver_patches.py:36: in _request
    self._conn = HTTPConnection(self._conn.host, self._conn.port)
E   AttributeError: 'RemoteConnection' object has no attribute '_conn'
```

**Comment by bubenkoff** [comment]
1.5.3 is out
curious, why you use remote webdriver? testing multiple browsers?

**Comment by pelme** [comment]
Thanks so much for this! I see that you added keep-alive which I think will be a big deal for our use case.

We run tests against Saucelabs to avoid having to maintain multiple VMs/browser versions by ourselves and we get a lot of screenshots, video recordings and a nice web ui to inspect failing tests.

My plan is to switch to xvfb+firefox for the bulk of our tests and then run nightly builds on saucelabs in IE/Safari/iOS etc.

Do you run everything locally? Single machine with xdist, or multiple? Do you find that failure screenshots provide enough information to track down failures?

**Comment by pelme** [comment]
Yay! keep-alive seems to cut the test run time in half... and still no time out errors or other failures (!!!)

**Comment by bubenkoff** [comment]
yep, i don't get why it's not enabled by default for remote webdriver...
well, in the end it's just one more compensation for pytest-splinter :)
glad that it helped you to be more productive, i know that is very frustrating to fight against your test suite which fails all the time...
especially for our case, as we use automatic merges, if tests are green
we run all tests 'locally', on like 15 vms in like 40 parallel processes, with ff webdriver only, for now
failure screenshots are fine enough, especially with html screenshots recently added, im sure it's good.
Of course we loose mobile testing, but that's easy to add (we'll talk separately about your experience :))

**Comment by pelme** [comment]
Yes, it's good to get decent defaults, there are too many of these small gotchas with browser tests that makes it painful to get it working.

HTML screenshots sounds useful to look around in the DOM, and is not something that Saucelabs does.

I'll buy you a bunch of beers on the next conference! :beers:
