### ISSUE TITLE
browser instance not clean 

### ISSUE THREAD

**Issue by miohtama** [pytest-dev/pytest-splinter#49]
I came across an issue I'd hope to get some help to resolve. pytest-splinter 1.6.6.

When using a the default `browser` fixture, something is being cached across the tests and `browser` instance is in fact not clean when the test starts. Particularly, OAuth2 login to an third party site (Facebook, others) made through the browser is still available in the next test and Facebook doesn't present the login page.

For example, I have two tests (`test_presto_login` and `test_presto_non_evaluated_user`) which login to a third party website using a `browser`. The latter test doesn't log in a different user, but OAuth provider (third party website) somehow remembers the login from the previous test and thus gives wrong authorization.

The workaround is to create a different browser instance for tests using different OAuth users, but I'd like to track down what is causing this behavior and make sure `browser` is cleaned up properly.

Any idea where I should start to poke this and see what's stored inside the browser which is not being cleaned up?

Below is the sample code:

    def do_presto_login(browser, presto_user=PRESTO_USER_WITH_RECOMMENDATION, presto_password=PRESTO_PASSWORD):
     
        b = browser

        assert b.is_text_present("Sign in to your account")

        b.fill("user[email]", presto_user)
        b.fill("user[password]", presto_password)
        b.find_by_css("input[name='commit']").click()

        # First time login pops up allow permission dialog.
        if b.is_text_present("Authorization required"):
            b.find_by_css("input[name='commit']").click()

    def test_presto_login(web_server, browser, DBSession, init):

        b = browser

        # Initiate Presto login with Authomatic
        b.visit("{}/login".format(web_server))
        b.find_by_css(".btn-login-prestodoctor").click()

        do_presto_login_if_needed(b)

    def test_presto_non_evaluated_user(web_server, browser, DBSession, init):

        b = browser

        # Initiate Presto login with Authomatic
        b.visit("{}/login".format(web_server))
        b.find_by_css(".btn-login-prestodoctor").click()

        do_presto_login_if_needed(b, presto_user=PRESTO_USER_WITHOUT_RECOMMENDATION)

As a workaround you can create another browser instance for the another OAuth user:

    @pytest.fixture
    def non_evaluated_user_browser(request, browser_instance_getter):
        return browser_instance_getter(request, non_evaluated_user_browser)

    def test_presto_non_evaluated_user(web_server, non_evaluated_user_browser, DBSession, init):

        b = non_evaluated_user_browser

        # Initiate Presto login with Authomatic
        b.visit("{}/login".format(web_server))
        b.find_by_css(".btn-login-prestodoctor").click()

        do_presto_login_if_needed(b, presto_user=PRESTO_USER_WITHOUT_RECOMMENDATION)

        assert b.is_text_present("You are now logged in")

**Comment by bubenkoff** [comment]
thanks for this, it's a good point to add to the documentation: by default, browser is session scoped (long living among various tests) and cookies are cleared on every test, BUT, only for CURRENT domain.
that's a limitation of selenium, when you call a method to delete cookies, it only does that for current domain, as i think it goes up to the browser security limitations as well. see http://stackoverflow.com/questions/16127496/selenium-webdriver-delete-cookies-on-all-domains
So for you, there are basically 2 ways:
- simplest, but slowest, switch to function-scoped browser, either by overriding a fixture `splinter_session_scoped_browser` to return False or just by passing a command line option `--splinter-session-scoped-browser=false`
- a bit more complicated, but smarter and faster: override a browser fixture like this:

```python 
@pytest.fixture
def browser(browser):
    browser.visit('your third party url')
    browser.cookies.delete()
    return browser
```
Im sure there's a place for improvement of pytest-splinter itself as well, for example, using this suggestion
http://stackoverflow.com/a/15179516/981494
just clean the directory with the cookies in the browser fixture
i'll work on this, until it's done, you can you the workarounds above
thanks again!

**Comment by bubenkoff** [comment]
hey @miohtama, can you please try to play with the `clean-cookies` branch installed, does it improve things?

**Comment by miohtama** [comment]
On it. Will report back shortly.

**Comment by miohtama** [comment]
I tried the current patch. Looks like `cookies.sqlite` is removed. It is not working and looks like there is no `cookies.sqlite` file there. The cookies are effectively stored in somewhere, though, because the issue is still present.

OSX, Firefox 40.

    > /Users/mikko/code/trees/venv/src/pytest-splinter/pytest_splinter/plugin.py(186)clean_cookies()
        185         if os.path.exists(path):
    --> 186             unlink(path)
        187 

    ipdb> os.listdir(browser.driver.profile.profile_dir,)
    ['.parentlock', 'addons.json', 'blocklist.xml', 'bookmarkbackups', 'browser_log1286667501345.txt', 'cache2', 'cert8.db', 'compatibility.ini', 'content-prefs.sqlite', 'crashes', 'directoryLinks.json', 'driver_log78985903884.txt', 'enumerate_devices.txt', 'extensions', 'extensions.ini', 'extensions.json', 'formhistory.sqlite', 'frequencyCap.json', 'gmp', 'gmp-gmpopenh264', 'key3.db', 'localstore.rdf', 'mimeTypes.rdf', 'minidumps', 'permissions.sqlite', 'places.sqlite', 'places.sqlite-shm', 'places.sqlite-wal', 'pluginreg.dat', 'prefs.js', 'profiler_log1117493635039.txt', 'safebrowsing', 'search-metadata.json', 'search.json', 'secmod.db', 'sessionCheckpoints.json', 'sessionstore-backups', 'startupCache', 'storage', 'thumbnails', 'times.json', 'user.js', 'webapps', 'webappsstore.sqlite', 'webappsstore.sqlite-shm', 'webappsstore.sqlite-wal', 'xulstore.json']

My theories

* Firefox writes out cookies.sqlite only on close and keeps this information in-process memory, thus deleting the file doesn't do any good

* Firefox has revamped its cookie engine and there is no longer cookies.sqlite

**Comment by miohtama** [comment]
I think it is for now enough to advise the users to visit every domain their browser touches and call underlying Selenium to clean cookies when the domain is active.

Maybe this issue should be resolved on Selenium level, as it is Selenium which lacks the functionality?

**Comment by bubenkoff** [comment]
yep, you're right, removing cookies.sqlite doesn't do anything
for complete cookie cleanup the only way is to work in 'browser environment' which is accessible only for extensions, there's an extension for cookie removal, but how to interact with it from the page environment - it should be prohibited due to security reasons, obviously

so for now i'll have a fixture with a list of additional urls to clean cookies on
so users can override it to add their ones

**Comment by bubenkoff** [comment]
another option btw is to always open a private window (via driver.send_keys(Keys.COMMAND + Keys.SHIFT + 'p') but it is really slow

**Comment by miohtama** [comment]
Does it clean cookies of last visited domain, first opened domain or do you have the details of the current functionality? I'd like to make an update to this in README, as looks like full cleanup is not going to be the way.

**Comment by bubenkoff** [comment]
it's the last visited domain
the one you mentioned last in browser.visit or browser.driver.get in the previous test
cookies will be cleaned up only for that domain

**Comment by miohtama** [comment]
Will try out this tonight.
