### ISSUE TITLE
improvement: save test failure stack trace side-by-side with screenshot

### ISSUE THREAD

**Issue by pjotal** [pytest-dev/pytest-splinter#50]
even though having screenshots is very handy, not all the time it is enough to let us figure out what caused the issue. in this scenario, having the failure stack trace side-by-side with the screenshot is very helpful.
therefore, this ticket suggests the creation of a cd line argument to let us save the test failure as a file which can go side-by-side with the screenshot (e.g. create_item.png , create_item.log) in order to easy the failure analysis.

**Comment by blueyed** [comment]
That would be similar to saving the html itself: https://github.com/pytest-dev/pytest-splinter/commit/cbb187308ee795a3ee8322d424020dd0a9569a7b

**Comment by pjotal** [comment]
@blueyed not really. i think you understood me wrong. i was not talking about the html snapshot but rather saving the test error itself (failure stacktrace) in a (log?) file. this is mainly because the default error report in pytest is displayed at the end of the run and its output is stdout. making it available at runtime separated per test (and this is where side-by-side to the png snapshot makes it even nicer) looks like a great improvement since it allow us to check the stacktrace while the tests are still running :)

**Comment by blueyed** [comment]
@pjotal 
I understood you correctly.. :)

I've just meant that the implementation for your idea would be similar - but instead of the html the stacktrace would be saved.

**Comment by pjotal** [comment]
oh ok. sorry for the misunderstanding :)

**Comment by bubenkoff** [comment]
wouldn't it be a somewhat wrong replacement for what pytest has natively?
eg xunit reporting?
if you use jenkins, it combines screenshots and test reports just fine - as
stated in the readme

**Comment by bubenkoff** [comment]
screenshots (both html and png) are those pytest can't obviously provide
that's why pytest-splinter adds them

**Comment by pjotal** [comment]
i personally don't see as a wrong replacement. the xunit report is just generated at the very end of the process and it's a consolidated report with all errors (split by test, of course).
i am not proposing a replacement at all. i am just proposing to output those errors on-the-fly (and not just at the end), in the same way you guys do with the screenshots and the html :)
this makes it easier and faster to check the failure stacktrace (we can't check then while the tests are still running) and also somehow covers the scenario where jenkins/process might fail before the xunit report is generated.
as i said, it's mainly useful when we have a long test suite run (e.g. our whole test suite here takes 1h+ to complete). in this scenario, having access to some failure stacktrace becomes very handy.

**Comment by bubenkoff** [comment]
well, i think it's cheap to add this kind of reporting
would you mind of PR?

**Comment by pjotal** [comment]
i wouldn't mind at all. let me know when you're done and i can download the code and test it for you :)

**Comment by reddypdl** [comment]
pytest-html is a great plug-in to generate beautiful html reports , more info @ https://github.com/davehunt/pytest-html, can it be integrated to splinter.

pytest-selenium already uses this plugin. more info @ https://github.com/davehunt/pytest-selenium

**Comment by bubenkoff** [comment]
Looks like a way to go indeed!

**Comment by bubenkoff** [comment]
so there's no need in implementing something in pytest-splinter - just use pytest-html plugin
