### ISSUE TITLE
screenshot is not generated when we use --splinter-session-scoped-browser=false

### ISSUE THREAD

**Issue by pjotal** [pytest-dev/pytest-splinter#51]
we noticed 2 inconsistencies while using --splinter-session-scoped-browser=false:
1. the screenshot is not created at all
2. the html is always output with 0 bytes

if we provide --splinter-session-scoped-browser=true everything is properly generated

**Comment by bubenkoff** [comment]
@pjotal would you mind working on this and making a PR?

**Comment by bubenkoff** [comment]
this should be fixed now in master, please check

**Comment by pjotal** [comment]
confirmed it's fixed :+1:  thanks

**Comment by bubenkoff** [comment]
1.7.2 is out
