### ISSUE TITLE
pytest_runtest_makereport uses deprecated __multicall__ argument

### ISSUE THREAD

**Issue by fagerbua** [pytest-dev/pytest-splinter#52]
Running pytest with pytest-splinter 1.7.0 installed causes the following pytest warning:

```'pytest_runtest_makereport' hook uses deprecated __multicall__ argument```

(pytest must be run with the `-rw` argument to see the actual warning message)

**Comment by bubenkoff** [comment]
thanks for reporting, PS is welcome :)
