### ISSUE TITLE
Disable Firefox welcome screen

### ISSUE THREAD

**Issue by miohtama** [pytest-dev/pytest-splinter#53]
Currently Firefox (profile) opens a welcome screen each time a new browser instance is created. This screen is not hosted locally and wastes CPU and bandwidth. To get rid of this we should set:

       profile.set_preference('startup.homepage_welcome_url.additional', '')

in `splinter_firefox_profile_preferences()`.

I can make a PR if there is nothing related to this going on already.

<img width="1034" alt="screen shot 2015-12-06 at 23 42 13" src="https://cloud.githubusercontent.com/assets/49922/11619756/78bba3bc-9c79-11e5-9152-009a4aecead7.png">

**Comment by bubenkoff** [comment]
please make a PR

**Comment by bubenkoff** [comment]
this is done and released in the latest version

**Comment by miohtama** [comment]
Thanks @bubenkoff - had missed your reply. Good work!
