### ISSUE TITLE
PhantomJS processes not terminating after testing

### ISSUE THREAD

**Issue by pydolan** [pytest-dev/pytest-splinter#60]
When using pytest-splinter with PhantomJS (installed via `npm install phantomjs-prebuilt`), I'm left with a new phantomjs process after each time I run `py.test` (e.g., `ps aux` may show dozens).  I'm using python 3.5, phantomjs 2.1.1, pytest 2.9.0, pytest-splinter 1.7.1, splinter 0.7.3.  

I'm not familiar enough with these systems to know where the bug actually lies, so if it isn't pytest-splinter, let me know what it might be instead. Thanks!

**Comment by bubenkoff** [comment]
can you please come up with a small reproducible test project for that?
