### ISSUE TITLE
browser.driver.save_screenshot doesn't save in splinter_screenshot_dir

### ISSUE THREAD

**Issue by aljosa** [pytest-dev/pytest-splinter#63]
after splinter_screenshot_dir is set, `browser.driver.save_screenshot('test.png')` still saves in current folder and not in path set by `splinter_screenshot_dir`.

```
@pytest.fixture(scope='session')
def splinter_screenshot_dir():
    [...]
    return path
```

**Comment by bubenkoff** [comment]
splinter_screenshot_dir is only supposed to be used by automatic screenshot making on the test error
what you try to do is a manual screenshot, and so just use that fixture and append an image name to it
