### ISSUE TITLE
Duplicate tmpdir fixtures causes --fixtures sorting logic to fail

### ISSUE THREAD

**Issue by martinpelikan** [pytest-dev/pytest-splinter#66]
It looks like something (recent) in pytest-splinter is creating a duplicate `tmpdir` fixture, and causes `py.test --fixtures` to fail when trying to sort the available fixtures. 

I can't tell if this is due to something unique/incorrect in `pytest-splinter`, or if `pytest` itself should be made more robust.

Please see the details I filed in: https://github.com/pytest-dev/pytest/issues/1651.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest-splinter/blob/master/pytest_splinter/plugin.py#L20 triggers this issue

importation of fixtures is always a bad idea

**Comment by bubenkoff** [comment]
@RonnyPfannschmidt 
cool, but what exactly is the proposed solution then?

**Comment by RonnyPfannschmidt** [comment]
@bubenkoff in that particular case for now use the tmpdir factory for pytest 3.1 we have a invocation scoped tmpdir fixture planned

**Comment by bubenkoff** [comment]
@martinpelikan please check with 1.7.4 which is just out

**Comment by martinpelikan** [comment]
@bubenkoff Confirmed working on 1.7.4, thanks!
