### ISSUE TITLE
Specify Firefox binary location

### ISSUE THREAD

**Issue by miohtama** [pytest-dev/pytest-splinter#77]
New Firefox versions require `geckodriver` for Selenium tests. However this Marionette based driver is not feature complete and not everything that use to work is functional anymore.

The solution is to downgrade Firefox. However if you run normal Firefox on the same computer there is a confusion about which Firefox binary to use. 

I'd like to provide a patch that allows you to specify the location of Firefox binary. Would you have any guidance for this what parts to touch?

**Comment by bubenkoff** [comment]
There's simply no need to bother with a patch - you can just set PATH accordingly so firefox binary will get the priority

**Comment by luzfcb** [comment]
after [Selenium [1]](https://pypi.python.org/pypi/selenium) version 3, [`geckodriver`[2]](https://github.com/mozilla/geckodriver/releases) binary should be in the PATH. Marionette is used by default on Selenium > 3.0

Selenium is a dependency of Splinter

[1] https://pypi.python.org/pypi/selenium
[2] https://github.com/mozilla/geckodriver/releases

**Comment by miohtama** [comment]
I am not sure if Selenium uses PATH for Firefox on OSX. Because I experimented it with not so good results. But let me double check.

**Comment by bubenkoff** [comment]
well, i used path manipulation earlier successfully, to pin certain version of the ff
