### ISSUE TITLE
Support for MS Edge is broken

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest-splinter#81]
MS Edge crashes when clearing cookies:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5751773/

This always happens on browser start in prepare_browser:
https://github.com/pytest-dev/pytest-splinter/blob/c4cf38683ee8eff0a6cecc0fb21c118d5cf1d34a/pytest_splinter/plugin.py#L411

The infinite retry behavior in prepare_browser (see #71, #72, #73) hides this error and restarts the browser infinitely.

**Comment by pelme** [comment]
From what I understand the cookie cleaning is somewhat broken in another way too:

* In session scoped browsers cookies is cleared at browser startup (when the cookies is already clean anyways) but since this happens in prepare_browser, it won't be called between tests.

* In function scoped browsers cookie cleanup happens, but it is not very useful since a clean browser is constructed for each test anyways.

My preferred solution would be to just avoid cookie cleaning on function-scoped browsers altogether even if `splinter_clean_cookies_urls` is configured, fix `splinter_clean_cookies_urls` to be called before each test with session scoped browsers and change the default of `splinter_clean_cookies_urls` to `['about:blank']` to preserve the existing behaviour. Users of MS Edge+session scoped browsers just have to set `splinter_clean_cookies_urls` to a real url or `[]` until the issue is fixed in edge/selenium.

(FYI I cannot use session scoped browsers at all since we store a bunch of stuff in localstorage which cannot be reliably cleared via webdriver APIs)

@bubenkoff thoughts?

**Comment by bubenkoff** [comment]
For session scoped browser prepare browser is Always called per test

**Comment by bubenkoff** [comment]
@pelme, please try related pull request and see if it solves both issues (retry and cookies)
