### ISSUE TITLE
splinter_failure does not always exists 

### ISSUE THREAD

**Issue by pelme** [pytest-dev/pytest-splinter#84]
We need to check that the attribute actually exists. This may happen when ctrl+c aborting a test run.

**Comment by bubenkoff** [comment]
is it still a problem?

**Comment by pelme** [comment]
I think so. It happened once or twice for me. I am not sure exactly how it happens but it has happened. Something like `getattr(request.node, 'splinter_failure', True)` instead of just checking `request.node.splinter_failure` should probably solve the problem.

It is hard to come up with a test for it though. :/

**Comment by bubenkoff** [comment]
should be fixed now
