### ISSUE TITLE
AttributeError: 'function' object has no attribute 'ensure'

### ISSUE THREAD

**Issue by ionelmc** [pytest-dev/pytest-splinter#94]
I've tried to make a patch but I don't get why all those branches are there. Why is `screenshot_dir` recreated in certain conditions?
```
[gw1] linux2 -- Python 2.7.12 /usr/bin/python2.7
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pytest_splinter/plugin.py", line 522, in _take_screenshot_on_failure
    splinter_screenshot_getter_png=splinter_screenshot_getter_png,
  File "/usr/local/lib/python2.7/dist-packages/pytest_splinter/plugin.py", line 376, in _take_screenshot
    screenshot_dir = session_tmpdir.ensure('screenshots', dir=True).strpath
AttributeError: 'function' object has no attribute 'ensure'
```

**Comment by bubenkoff** [comment]
good catch, session_tmpdir needs to be a parameter of that function and passed from the fixture `session_tmpdir`
which branches do you mean?

**Comment by bubenkoff** [comment]
try 1.8.4

**Comment by ionelmc** [comment]
Branches as in `if` statements :)

**Comment by bubenkoff** [comment]
the if is for xdist so when it's on remote node it needs to be created both on remote and local sides

**Comment by bubenkoff** [comment]
sorry for making mess - 1.8.5 should work

**Comment by ionelmc** [comment]
@bubenkoff 1.8.5 ain't on pypi yet, upload failed?

**Comment by bubenkoff** [comment]
sorry again - missed that, now it's there

**Comment by ionelmc** [comment]
No problem, thanks for the quick fixes :)
